fix:최초dev,update:번역기능
Kimsounggu/T1F4 pull request #10
Opened 2024-05-07 13:02 UTC by LeeHareum

번역토글 기능추가

2024-05-07 13:07 UTC, Kimsounggu approved these changes
고생하셨습니당~

2024-05-08 00:14 UTC, DAEWOOYANG0310 commented
수고하셨습니다!

2024-05-08 00:16 UTC, riverSun1 approved these changes
고생하셨어요!💪

2024-05-08 03:33 UTC, hyeonseok98 requested changes
merge 살짝 보류 부탁드릴게요!

2024-05-08 07:28 UTC, DAEWOOYANG0310 approved these changes

2024-05-08 15:40 UTC, closed without merging